checks
git-svn-id: svn://svn.code.sf.net/p/gphoto/code/trunk@7016 67ed7778-7388-44ab-90cf-0a291f65f57c

diff --git a/CVSROOT/common-error-check b/CVSROOT/common-error-check
--- a/CVSROOT/common-error-check
+++ b/CVSROOT/common-error-check
@@ -4,12 +4,51 @@
 repository="$1"
 shift
 
+check_Makefile.am() {
+	[ "$basename" == "Makefile.am" ] || return 0
+	errors=0
+	if grep -q -E '^SUBDIRS[[:space:]]*=.*\<intl\>' "$file"; then
+		echo "ERROR in file $file:"
+		echo "A CVS Makefile.am SUBDIRS line may not contain the \"intl\" subdirectory"
+		echo "The \"intl\" subdirectory is already added by autogen.sh/gettextize."
+		errors=$(( $errors + 1 ))
+	fi
+	return "$errors"
+}
+
+check_configure.in() {
+	[ "$basename" == "configure.in" ] || return 0
+	errors="0"
+	return "$errors"
+}
+
+error_files=""
+error_count=0
 while [ "$1" != "" ]
 do
 	file="$1"
-	echo "Checking file: $file"
-	cat "$file"
+	basename="$(basename "$file")"
+	for check in \
+		check_Makefile.am \
+		check_configure.in
+	do
+		if "$check" "$file"; then
+			error_files="$error_files $file"
+			error_count=$(( $error_count + 1 ))
+		fi
+	done
+
 	shift
 done
 
+if [ "$error_count" -gt "0" ]; then
+	echo "CVS commit denied because of $error_count errors in your files:"
+	for file in ${error_files}; do
+		echo "    $file"
+	done
+	echo "View above error messages for details."
+	exit 1
+fi
+
 exit 0
+
